from pathlib import Path

from cybergraph.pr_comment import generate_pr_comment, write_pr_comment


def test_generate_pr_comment_returns_markdown_for_non_git_repo(tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    repo.mkdir()
    (repo / "app.py").write_text("def app():\n    return 1\n", encoding="utf-8")

    comment = generate_pr_comment(repo)

    assert "CyberGraph Security Review" in comment
    assert "| Changed files | 0 |" in comment
    assert "Layer Summary" in comment


def test_write_pr_comment_creates_file(tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    repo.mkdir()

    output = write_pr_comment(repo, tmp_path / "comment.md")

    assert output.exists()
    assert "Generated by CyberGraph" in output.read_text(encoding="utf-8")
