import subprocess
from pathlib import Path

from cybergraph.pr_comment import generate_pr_comment, write_pr_comment


def test_generate_pr_comment_returns_markdown_for_non_git_repo(tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    repo.mkdir()
    (repo / "app.py").write_text("def app():\n    return 1\n", encoding="utf-8")

    comment = generate_pr_comment(repo)

    assert "CyberGraph Security Review" in comment
    assert "What Changed" in comment
    assert "Why It Matters" in comment
    assert "What To Check Next" in comment
    assert "| Changed files | 0 |" in comment
    assert "Layer Summary" in comment


def test_write_pr_comment_creates_file(tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    repo.mkdir()

    output = write_pr_comment(repo, tmp_path / "comment.md")

    assert output.exists()
    assert "Generated by CyberGraph" in output.read_text(encoding="utf-8")


def test_generate_pr_comment_includes_reachable_risk_deltas(tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    repo.mkdir()
    _git(repo, "init")
    (repo / "app.py").write_text("def app():\n    return 1\n", encoding="utf-8")
    _git(repo, "add", "app.py")
    _git(repo, "-c", "user.name=Test", "-c", "user.email=test@example.com", "commit", "-m", "base")
    (repo / "app.py").write_text(
        "@app.get('/search')\n"
        "def app(request):\n"
        "    q = request.query['q']\n"
        "    return db.execute('select ' + q)\n",
        encoding="utf-8",
    )

    comment = generate_pr_comment(repo, base="HEAD")

    assert "Reachable Risk Deltas" in comment
    assert "`added`" in comment
    assert "db.execute" in comment


def _git(repo: Path, *args: str) -> None:
    subprocess.run(["git", *args], cwd=repo, check=True, capture_output=True, text=True)
