import subprocess
from pathlib import Path
from unittest.mock import patch

from cybergraph.pr_comment import _reason_line, generate_pr_comment, write_pr_comment
from cybergraph.security.assurance import (
    ASSURANCE_BENCHMARKED,
    ASSURANCE_BETA,
    ASSURANCE_UNSUPPORTED,
    EVIDENCE_NONE,
    EVIDENCE_PARTIAL,
    EVIDENCE_STRONG,
    REASON_UNRESOLVED,
    STATUS_UNRESOLVED,
    has_epistemic_upgrade,
    phrase_for,
)
from cybergraph.security.verdict import (
    STATE_REVIEW,
    Provenance,
    Reason,
    Verdict,
    select_primary_reason,
)


def test_generate_pr_comment_returns_markdown_for_non_git_repo(tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    repo.mkdir()
    (repo / "app.py").write_text("def app():\n    return 1\n", encoding="utf-8")

    comment = generate_pr_comment(repo)

    assert "CyberGraph Security Review" in comment
    assert "What Changed" in comment
    assert "Why It Matters" in comment
    assert "What To Check Next" in comment
    assert "| Changed files | 0 |" in comment
    assert "Layer Summary" in comment


def test_write_pr_comment_creates_file(tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    repo.mkdir()

    output = write_pr_comment(repo, tmp_path / "comment.md")

    assert output.exists()
    assert "Generated by CyberGraph" in output.read_text(encoding="utf-8")


def test_generate_pr_comment_includes_reachable_risk_deltas(tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    repo.mkdir()
    _git(repo, "init")
    (repo / "app.py").write_text("def app():\n    return 1\n", encoding="utf-8")
    _git(repo, "add", "app.py")
    _git(repo, "-c", "user.name=Test", "-c", "user.email=test@example.com", "commit", "-m", "base")
    (repo / "app.py").write_text(
        "@app.get('/search')\n"
        "def app(request):\n"
        "    q = request.query['q']\n"
        "    return db.execute('select ' + q)\n",
        encoding="utf-8",
    )

    comment = generate_pr_comment(repo, base="HEAD")

    assert "Reachable Risk Deltas" in comment
    assert "`added`" in comment
    assert "db.execute" in comment


def _git(repo: Path, *args: str) -> None:
    subprocess.run(["git", *args], cwd=repo, check=True, capture_output=True, text=True)


def _dropped_guard_and_beta_stack_verdict() -> Verdict:
    """A hand-built Verdict: a dropped-auth-guard policy reason (before/after
    boundary story, reason_class == "") plus a beta-stack epistemic reason
    (unresolved, low-assurance language) that must never read as "confirmed"."""
    boundary_reason = Reason(
        headline=(
            "`/admin/users` no longer has a login check. "
            "It had one on the base branch."
        ),
        rule_id="/admin/users",
        kind="promise_broken",
    )
    beta_reason = Reason(
        headline="Unsafe database queries: string-built SQL reaches a Go handler.",
        file_path="services/orders/handler.go",
        line=42,
        rule_id="sql_construction",
        kind="check_unknown",
        status=STATUS_UNRESOLVED,
        evidence=EVIDENCE_PARTIAL,
        assurance=ASSURANCE_BETA,
        impact="high",
        reason_class=REASON_UNRESOLVED,
        protected=False,
    )
    return Verdict(
        state=STATE_REVIEW,
        reasons=(boundary_reason, beta_reason),
        checks=(),
        not_evaluated=(),
        provenance=Provenance(),
        gate="",
        primary_reason=REASON_UNRESOLVED,
    )


def test_generate_pr_comment_is_a_projection_of_the_verdict(tmp_path: Path) -> None:
    """Law 4: the PR comment renders check_change's Verdict, it never re-derives
    its own decision. Mock check_change and assert its reasons show up verbatim."""
    repo = tmp_path / "repo"
    repo.mkdir()
    (repo / "app.py").write_text("def app():\n    return 1\n", encoding="utf-8")
    verdict = _dropped_guard_and_beta_stack_verdict()
    boundary_reason, beta_reason = verdict.reasons

    with patch("cybergraph.pr_comment.check_change", return_value=verdict) as mock_check:
        comment = generate_pr_comment(repo, base="HEAD~1")

    mock_check.assert_called_once_with(repo.resolve(), base="HEAD~1")

    # Decision, driven by verdict.state.
    assert "`REVIEW`" in comment

    # primary_reason worded via assurance.phrase_for -- never hand-written.
    phrase = phrase_for(beta_reason.status, beta_reason.evidence, beta_reason.assurance)
    assert phrase.capitalize() in comment
    assert beta_reason.headline in comment

    # Evidence citation: file_path:line for the primary reason.
    assert "services/orders/handler.go:42" in comment

    # Before/after boundary line for the dropped-guard policy reason.
    assert boundary_reason.headline in comment

    # Gate line: the CLI's exact policy layer, applied here since check_change
    # always returns gate="" (Law 7). Two REVIEW reasons and no protected
    # boundary hit -> the default verification config gates this "warn", and a
    # non-blocking gate over a REVIEW must say so explicitly, never read ACCEPT.
    assert "`warn`" in comment
    assert "not blocking per policy" in comment


def test_generate_pr_comment_beta_stack_finding_has_no_forbidden_upgrade(
    tmp_path: Path,
) -> None:
    """The rendered line for the beta-stack (unresolved) finding must never
    contain an epistemic-upgrade word -- checked against that finding's own
    rendered text, not generic reviewer-checklist boilerplate elsewhere in
    the comment that isn't a claim about this finding's status."""
    repo = tmp_path / "repo"
    repo.mkdir()
    verdict = _dropped_guard_and_beta_stack_verdict()
    beta_reason = verdict.reasons[1]
    rendered_reason_line = _reason_line(beta_reason)

    with patch("cybergraph.pr_comment.check_change", return_value=verdict):
        comment = generate_pr_comment(repo, base="HEAD~1")

    assert rendered_reason_line in comment
    assert has_epistemic_upgrade(rendered_reason_line, beta_reason.status) is False


def test_generate_pr_comment_headlines_the_same_reason_as_select_primary_reason(
    tmp_path: Path,
) -> None:
    """Regression for a Law-4 divergence: two reasons share ``reason_class ==
    "unresolved"``, inserted low-priority-first. The primary line must be the
    one ``verdict.py``'s own trust x impact tiebreak (``select_primary_reason``)
    picks -- NOT the first one in insertion order -- so the PR comment can
    never headline a lower-priority finding than `cybergraph check` would for
    the identical Verdict."""
    repo = tmp_path / "repo"
    repo.mkdir()

    low_priority = Reason(
        headline="A low-priority thing CyberGraph could not fully evaluate.",
        file_path="a.py",
        line=1,
        rule_id="cloud_configuration",
        kind="check_unknown",
        status=STATUS_UNRESOLVED,
        evidence=EVIDENCE_NONE,
        assurance=ASSURANCE_UNSUPPORTED,
        impact="low",
        reason_class=REASON_UNRESOLVED,
        protected=False,
    )
    high_priority = Reason(
        headline="A high-priority thing CyberGraph could not fully evaluate.",
        file_path="b.py",
        line=2,
        rule_id="declared_login_rules",
        kind="check_unknown",
        status=STATUS_UNRESOLVED,
        evidence=EVIDENCE_STRONG,
        assurance=ASSURANCE_BENCHMARKED,
        impact="critical",
        reason_class=REASON_UNRESOLVED,
        protected=False,
    )
    # Inserted low-priority first: a naive "first reason of this class" pick
    # would wrongly headline `low_priority`.
    verdict = Verdict(
        state=STATE_REVIEW,
        reasons=(low_priority, high_priority),
        checks=(),
        not_evaluated=(),
        provenance=Provenance(),
        gate="",
        primary_reason=REASON_UNRESOLVED,
    )

    expected = select_primary_reason(verdict)
    assert expected is high_priority  # sanity: verdict.py itself picks the high one

    with patch("cybergraph.pr_comment.check_change", return_value=verdict):
        comment = generate_pr_comment(repo, base="HEAD~1")

    assert high_priority.headline in comment
    assert "b.py:2" in comment
    assert low_priority.headline not in comment
    assert "a.py:1" not in comment
