"""Pull request comment generation."""

from __future__ import annotations

from pathlib import Path

from cybergraph.graph import GraphStore
from cybergraph.security.layers import summarize_layers
from cybergraph.security.review import review_security_delta


def generate_pr_comment(repo_root: Path, base: str = "HEAD~1") -> str:
    repo_root = repo_root.resolve()
    review = review_security_delta(repo_root, base=base)
    layers = summarize_layers(repo_root)
    store = GraphStore.open_for_repo(repo_root)
    try:
        counts = store.counts()
        top_findings = store.conn.execute(
            """
            SELECT rule_id, severity, message, file_path, line_start
            FROM findings
            ORDER BY CASE severity
                WHEN 'critical' THEN 0 WHEN 'high' THEN 1 WHEN 'medium' THEN 2 ELSE 3 END,
                file_path,
                line_start
            LIMIT 5
            """
        ).fetchall()
    finally:
        store.close()

    risk = _risk(review)
    lines = [
        "## CyberGraph Security Review",
        "",
        f"**Risk:** `{risk}`",
        "",
        "| Metric | Count |",
        "|---|---:|",
        f"| Changed files | {len(review.changed_files)} |",
        f"| Findings in changed files | {review.finding_count} |",
        f"| Changed entrypoints | {len(review.changed_entrypoints)} |",
        f"| Changed sink edges | {len(review.changed_sink_edges)} |",
        f"| Changed attack paths | {review.attack_path_count} |",
        f"| Total graph nodes | {counts['nodes']} |",
        f"| Total graph edges | {counts['edges']} |",
        f"| Total findings | {counts['findings']} |",
        "",
        "### Layer Summary",
        "",
        "| Layer | Nodes | Edges | Findings |",
        "|---|---:|---:|---:|",
    ]
    for layer in layers:
        if layer.node_count or layer.edge_count or layer.finding_count:
            lines.append(
                f"| {layer.label} | {layer.node_count} | {layer.edge_count} | {layer.finding_count} |"
            )

    if review.changed_entrypoints:
        lines.extend(["", "### Changed Entrypoints", ""])
        lines.extend(f"- `{entrypoint}`" for entrypoint in review.changed_entrypoints[:10])
    if review.changed_sink_edges:
        lines.extend(["", "### Changed Sink Edges", ""])
        lines.extend(f"- `{sink}`" for sink in review.changed_sink_edges[:10])
    if top_findings:
        lines.extend(["", "### Top Findings", ""])
        for finding in top_findings:
            location = f"{finding['file_path']}:{finding['line_start']}" if finding["file_path"] else "-"
            lines.append(
                f"- `{finding['severity']}` `{finding['rule_id']}` at `{location}`: "
                f"{finding['message']}"
            )
    lines.extend(
        [
            "",
            "Artifacts: download `cybergraph-report.html` from this workflow run for the full report.",
            "",
            "<sub>Generated by CyberGraph.</sub>",
        ]
    )
    return "\n".join(lines)


def write_pr_comment(repo_root: Path, output: Path, base: str = "HEAD~1") -> Path:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(generate_pr_comment(repo_root, base=base), encoding="utf-8")
    return output


def _risk(review) -> str:
    if review.attack_path_count or review.finding_count > 3:
        return "high"
    if review.finding_count or review.changed_sink_edges or review.changed_entrypoints:
        return "medium"
    return "low"
